[tool.poetry]
name = "tesla_telemetry_distributor"
version = "0.1.0"
description = "Converts Tesla telemetry streams from a Tesla telemetry supplier to other methods"
authors = ["Erik Hendrix <hendrix_erik@hotmail.com>"]
license = "Apache License 2.0"
readme = "README.md"
repository = "https://github/com/ehendrix23/teslemetry-teslamate"
classifiers = [
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: Apache Software License",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: Implementation :: CPython",
	"Programming Language :: Python :: Implementation :: PyPy",
]

[tool.poetry.dependencies]
python = "^3.12"
tesla-fleet-api = "0.9.5"
teslemetry-stream = "0.6.6"
aiohttp_remotes = "1.3.0"
aiohttp = "3.11.11"

[tool.poetry.dev-dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
